name: abaplint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  abaplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Run abaplint
        run: npx --yes @abaplint/cli@2.120.68 abaplint.json
